name: "PHP Code Sniffer"

on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
          
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs, cs2pr
          
      - name: Check diff
        uses: technote-space/get-diff-action@v6
        with:
          CHECK_ONLY_COMMIT_WHEN_DRAFT: true
          FORMAT: json
      - run: |
         curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
         scope=`echo '${{ env.GIT_DIFF }}' | jq -r .[]`
         phpcs $scope --standard=phpcs.xml -q --report-full --report-checkstyle=phpcs-report.xml
#         phpcs $scope --standard=phpcs.xml --runtime-set ignore_errors_on_exit 3 --runtime-set ignore_warnings_on_exit 3 --report-full --report-checkstyle=phpcs-report.xml
         
      - name: PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
