name: Lint

on: pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        run: |
         cat $GITHUB_EVENT_PATH
         git diff
