name: "PHP Code Sniffer"

on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
          
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs, cs2pr
          
      - name: Check diff
        uses: technote-space/get-diff-action@v6
        with:
          CHECK_ONLY_COMMIT_WHEN_DRAFT: true
          FORMAT: json
      - run: |
         curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
         scope=`echo '${{ env.GIT_DIFF }}' | jq -r .[]`
         phpcs $scope --standard=phpcs.xml --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 -q --report-full --report-checkstyle=phpcs-report.xml
         phpcs $scope --standard=phpcs.xml --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 --report=json > load
         errors=`cat load | jq .totals.errors`
         warnings=`cat load | jq .totals.warnings`
         echo "| Level | Count |" > comment.md
         echo "| -----: | -----: |" >> comment.md
         echo "| ERROR | $errors |" >> comment.md
         echo "| WARNING | $warnings |" >> comment.md
         cat comment.md
         pwd && ls -l comment.md
#         phpcs $scope --standard=phpcs.xml --runtime-set ignore_errors_on_exit 3 --runtime-set ignore_warnings_on_exit 3 --report-full --report-checkstyle=phpcs-report.xml

      - name: Comment
        uses: NejcZdovc/comment-pr@v1
        with:
         file: "/home/runner/work/test/test/comment.md"
        env:
           GITHUB_TOKEN: ${{secrets.GH_BOT_TOKEN}}

      - name: PHPCS results in PR
        run: cs2pr ./phpcs-report.xml

